# Generated by Django 4.1.7 on 2023-04-10 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickethub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketFootball',
            fields=[
                ('F_name', models.CharField(max_length=10)),
                ('L_name', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TicketPlane',
            fields=[
                ('F_name', models.CharField(max_length=10)),
                ('L_name', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
