# Generated by Django 4.1.7 on 2023-04-10 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TicketCinema',
            fields=[
                ('F_name', models.CharField(max_length=10)),
                ('L_name', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
