# Generated by Django 4.1.7 on 2023-04-03 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
