# Generated by Django 4.1.7 on 2023-04-10 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0002_login_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('F_name', models.CharField(max_length=20)),
                ('L_name', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
                ('age', models.IntegerField()),
                ('idd', models.IntegerField()),
            ],
        ),
    ]
